import { Dimensions, StyleSheet } from "react-native";
import colors from "../../styles/colors";
import {
  height,
  moderateScale,
  scale,
  textScale,
  verticalScale,
} from "../../styles/responsiveSize";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: Math.round(Dimensions.get("window").height),
    backgroundColor: colors.white,
  },
  header: {
    marginHorizontal: moderateScale(16),
    marginTop: moderateScale(60),
    height: moderateScale(50),
    flexDirection: "row",
    backgroundColor: colors.white,
    justifyContent: "space-between",
    alignItems: "center",
  },
  menuIcon: {
    height: moderateScale(24),
    width: moderateScale(24),
  },
  layout: {
    flex: 1,
  },
  logo: {
    width: moderateScale(250),
    height: moderateScale(52),
    alignSelf: "center",
  },
  footer: {
    height: moderateScale(115),
    backgroundColor: colors.white,
  },
  map: {
    flex: 1,
  },
  sliderContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: moderateScale(16),
    height: moderateScale(35),
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderColor: colors.borderColor,
  },
  sliderStyle: {
    width: "80%",
    shadowColor: colors.black1,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.5,
    shadowRadius: 1.41,
    elevation: 2,
  },
  miles: {
    color: colors.black,
    fontSize: textScale(10),
    fontWeight: "400",
    textShadowColor: colors.black1,
    textShadowOffset: {
      width: 0,
      height: 4,
    },
    textShadowRadius: 5,
    elevation: 4,
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginHorizontal: moderateScale(16),
    backgroundColor: colors.white,
    marginTop: moderateScale(5),
  },
  tab: {
    width: moderateScale(59),
    height: moderateScale(53),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: moderateScale(8),
    backgroundColor: colors.white,
  },
  tabPressed: {
    width: moderateScale(59),
    height: moderateScale(53),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: moderateScale(8),
    backgroundColor: colors.background,
  },
  tabText: {
    color: colors.black,
    fontSize: textScale(10),
    fontWeight: "400",
    paddingTop: moderateScale(4),
  },
  mapFunctionalities: {
    position: "absolute",
    bottom: verticalScale(150),
    right: scale(5),
    width: moderateScale(70),
    borderRadius: moderateScale(15),
    backgroundColor: colors.white,
    shadowColor: colors.black1,
    shadowOffset: {
      width: 0,
      height: moderateScale(4),
    },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 2,
  },
  iconSize: {
    marginVertical: moderateScale(10),
    marginHorizontal: moderateScale(20),
  },
  filterText: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  filterTextStyle: {
    fontSize: textScale(20),
    fontWeight: "bold",
  },
  heading: {
    fontSize: textScale(20),
    fontWeight: "bold",
    marginTop: moderateScale(20),
  },
  nameCont: {
    height: moderateScale(30),
    paddingHorizontal: moderateScale(10),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: moderateScale(15),
    borderWidth: 1,
    borderColor: colors.borderColor,
    marginTop: verticalScale(10),
    marginRight: scale(10),
    flexDirection: "row",
  },
  artistContainer: {
    marginTop: verticalScale(10),
    marginLeft: scale(10),
  },
  selectedArtist: {
    backgroundColor: colors.logoColor,
  },
  artistText: {
    fontSize: textScale(12),
    fontWeight: "400",
    color: colors.black,
  },
  selectedArtistText: {
    color: colors.white,
  },

  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(22),
  },
  modalView: {
    backgroundColor: colors.white,
    borderRadius: moderateScale(20),
    paddingHorizontal: scale(28),
    paddingVertical: verticalScale(20),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  item1: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: colors.borderColor,
    paddingBottom: verticalScale(20),
    marginTop: verticalScale(20),
  },
  headingTitle: {
    fontSize: textScale(18),
    fontWeight: "200",
    color: colors.black,
  },
  switchCont: {
    width: moderateScale(82),
    paddingHorizontal: moderateScale(10),
    height: moderateScale(37),
    borderRadius: moderateScale(30),
    backgroundColor: colors.black,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  pickerStyle: {
    height: 50,
    width: 150,
    backgroundColor: colors.white, // Set the background color to white or any other desired color
  },
  
  onStyle: {
    width: moderateScale(26),
    height: moderateScale(19),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: moderateScale(12),
  },
  keyText: {
    fontSize: textScale(12),
    fontWeight: "400",
    color: colors.white,
    textAlign: "center",
  },
  commonLayout: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: colors.borderColor,
    paddingBottom: verticalScale(20),
    marginTop: verticalScale(20),
  },
  arrow: {
    height: moderateScale(20),
    width: moderateScale(20),
  },
  applyButtonCont: {
    height: moderateScale(40),
    backgroundColor: colors.logoColor,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: moderateScale(10),
    marginTop: verticalScale(20),
  },

  applyText: {
    fontSize: textScale(18),
    fontWeight: "200",
    color: colors.white,
  },
  searchBarCont: {
    position: "absolute",
    top: moderateScale(120),
    width: "100%",

    flexDirection: "row",
    paddingHorizontal: scale(16),
  },
  filterCont: {
    height: moderateScale(40),
    width: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    marginTop: verticalScale(3),
    shadowColor: colors.black1,
    shadowOffset: {
      width: 0,
      height: moderateScale(4),
    },
    shadowOpacity: 0.5,
    shadowRadius: 1.41,
    elevation: 2,
  },
  searchBar: {
    height: moderateScale(34),
    flexDirection: "row",
    alignItems: "center",
    width: "85%",
    backgroundColor: colors.white,
    borderRadius: moderateScale(55),
    shadowColor: colors.black1,
    shadowOffset: {
      width: 0,
      height: moderateScale(4),
    },
    shadowOpacity: 0.5,
    shadowRadius: 1.41,
    elevation: 2,
  },
  bottomContainer: {
    backgroundColor: colors.white,
    padding: moderateScale(16),
    borderTopLeftRadius: moderateScale(10),
    borderTopRightRadius: moderateScale(10),
  },
  container2: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: scale(20),
    marginTop: verticalScale(5),
    marginBottom: verticalScale(20),
  },
  shareIcon: {
    width: moderateScale(30),
    height: moderateScale(30),
    marginRight: scale(7),
  },
  textStyle: {
    fontSize: textScale(18),
    color: colors.black,
    marginLeft: scale(10),
  },
  noEventText: {
    fontSize: textScale(18),
    color: colors.black,
  },
  noEventCont: {
    justifyContent: "center",
    alignItems: "center",
    height: height / 4,
  },
  flatlistCont: {
    flex: 1,
    marginTop: verticalScale(20),
    marginBottom: verticalScale(20),
  },
  activityIndicator: {
    height: height / 4,
    justifyContent: "center",
    alignItems: "center",
  },
  card: {
    flexDirection: "row",
    marginVertical: moderateScale(10),
    backgroundColor: colors.white,
  },
  image: {
    width: moderateScale(141),
    height: moderateScale(127),
    borderRadius: moderateScale(10),
  },
  cardTitle: {
    fontSize: textScale(15),
    fontWeight: "200",
    color: colors.black,
    paddingLeft: scale(11),
  },
  cardSubTitle: {
    fontSize: textScale(15),
    fontWeight: "300",
    color: colors.black,
    paddingLeft: scale(11),
    paddingTop: verticalScale(12),
  },
  cardText: {
    flex: 1,
    flexDirection: "column",
    paddingLeft: scale(10),
  },
  markerStyle: {
    width: moderateScale(30),
    height: moderateScale(30),
  },
});

export default styles;
